### PR TITLE
Revert jest@v27 to jest@v26

### PR DESCRIPTION
**Pull request by diogotorres97**
Revert bump jest to v27. https://github.com/uphold/uphold-scripts/pull/43/files

Issues: 

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TCPWRAP

      13 | afterEach(() => {
      14 |   return Promise.all([
    > 15 |     db.sequelize.query('DELETE FROM "price_alerts"'),
         |                  ^
      16 |     db.sequelize.query('DELETE FROM "user_assets"'),
      17 |     db.sequelize.query('DELETE FROM "sms_events"')
      18 |   ]);
```

### CODE REVIEW

**Comment by satazor** [comment]
There seems to be a lot of bugs in Jest v27 due to detection of open handles. As an example, I'm having issues with using Mali in tests, even if I call `app.close()` at the end. I know this is not an issue with the code because the node.js process exists normally.

We should indeed rever to 26 until Jest figures this out.

**Comment by Americas** [comment]
Can you share a PR/repo where that happens?

**Comment by diogotorres97** [comment]
> Can you share a PR/repo where that happens?

https://github.com/uphold/notification-service/runs/5495015421?check_suite_focus=true#step:7:324

**Comment by satazor** [comment]
https://github.com/uphold/reward-service

Remove the Jest override in the package.json, at the bottom, and run the tests like indicated in the README.

**Comment by Americas** [comment]
Ok, I have seen that problem in other repos.

Just a note though, why run tests by default with `--detectOpenHandles`? I see that option as useful to help debug when tests don't cleanup correctly, but not so much for just running tests.

**Comment by diogotorres97** [comment]
Closing, we think it is better to remove `--detectOpenHandles` flag instead.

**Pull request closed without merging**
